### ISSUE TITLE
Converter crashing on WMO without MOMT chunk

### ISSUE THREAD

**Issue by miirak** [MaxtorCoder/MultiConverter#9]
I've tried to convert a WMO from 4.3.4 and got this error which I think due to no MOMT chunk on that model:

```
   at MultiConverter.Lib.Listfile.LookupFilename(UInt32 id, String extension, String modelname, String downloadExtension) in .D:\MultiConverter\MultiConverter.Lib\Util\Listfile.cs:line 90
   at MultiConverter.Lib.Converters.WMORootConverter.AddFilename(UInt32 fdid) in .D:\MultiConverter\MultiConverter.Lib\Converters\WMOConverter.cs:line 325
   at MultiConverter.Lib.Converters.WMORootConverter.ReadMOMT(Int32 pos) in .D:\MultiConverter\MultiConverter.Lib\Converters\WMOConverter.cs:line 244
   at MultiConverter.Lib.Converters.WMORootConverter.Fix() in .D:\MultiConverter\MultiConverter.Lib\Converters\WMOConverter.cs:line 45
   at MultiConverter.GUI.ConverterForm.<>c__DisplayClass8_0.<FixList>b__0(Object sender, DoWorkEventArgs e) in .D:\MultiConverter\MultiConverter.GUI\Form1.cs:line 145
```

**Comment by MaxtorCoder** [comment]
Stop converting lower versions than BFA/Shadowlands.

**Comment by miirak** [comment]
Then remove the file support table, benchod xD
